### ISSUE TITLE
Feature request: Make exposed port configurable

### ISSUE THREAD

**Issue by rdrongow** [angelnu/docker-ccu2#1]
This works just great. Thanks a lot! I tried it today and even though I had no experience with docker it worked right away. My production setup includes an nginx reverse proxy, which is listening on port 80 on the same rpi. I thought it should be easy to change the ccu2-docker port to something else but this seems to be more complicated. If you could point me to the right direction, I would love to provide a PR.

**Comment by holgerimbery** [comment]
@rdrongow: Have a look on line 118 of build.sh and change the exposed ports...

**Comment by rdrongow** [comment]
thx @holgerimbery. I found those already and tried to change the forwarding from 80 to 8080. But there's no effect. In the process list I find, that lighthttpd is listening to port 80 even if I remove the `-p 80:80` from `docker run`.

**Comment by holgerimbery** [comment]
@rdrongow: have you tried "-p 8080:80" ?  -p host_port:container_port

**Comment by rdrongow** [comment]
@holgerimbery: yes. I think the `--net=host` is the problem as it exposes the whole network, when I understand it correctly from the docker documentation. (https://docs.docker.com/engine/reference/run/#network-host)

**Comment by rdrongow** [comment]
A `docker run --name $DOCKER_ID --net=bridge -tid -p 8080:80 -p 2001:2001 --device=${SERIAL_DEVICE}:/dev/mmd_bidcos -v /sys/devices:/sys/devices -v /sys/class/gpio:/sys/class/gpio -v ${DOCKER_CCU2_DATA}:/usr/local ccu2` worked for me. I could provide a pull request and make network mode and port forwarding configurable. Let me know, if you're interested.

**Comment by angelnu** [comment]
The settings such as the exposed port are set at build time: at restart ccu2.service restarts the container with the same settings.

I will add two variables to the build.sh to make easier to change these values. Then you can change them and call build.sh again.

Example: `CCU2_REGA_PORT=8080 ./buid.sh`
