### ISSUE TITLE
Upgrade docker image to latest CCU2 release

### ISSUE THREAD

**Issue by omo2002** [angelnu/docker-ccu2#10]
Currently the prebuilt image is on release 2.25.15, in the meanwhile 2.27.8 and even 2.29.11 is about to be released. Could you please provide an updated docker image ?

**Comment by angelnu** [comment]
2.27.8 is on Docker Hub: https://hub.docker.com/r/angelnu/ccu2/tags/

I will upload 2.29.11

**Comment by angelnu** [comment]
2.29.11 is up - please give it a try.
