### ISSUE TITLE
cp: cannot stat 'enableCCUDevices.sh': No such file or directory

### ISSUE THREAD

**Issue by 7oku** [angelnu/docker-ccu2#11]
Hi there, 

when build.sh reaches line 129 to copy the "enableCCUDevices.sh" file, it is still in the build subdirectory. 
Visible when adding something like `pwd && ls` one line before:

> Start ccu2 service
> /home/pi/docker-ccu2/build
> ccu2-2.29.23.tgz  docker_build	rootfs-2.29.23.ubi  ubi  ubi-2.29.23.tgz  ubi_reader
> cp: cannot stat 'enableCCUDevices.sh': No such file or directory

Had to add a `cd ..` prior that command. Just wanted to let you know ...

**Comment by TomTom101** [comment]
Be sure to go into su interactive mode before running build.sh

`sudo -i`

Othwise, when you `sudo build.sh`, root will `cd` into its home directory, leaving the folder where the script is.

**Comment by angelnu** [comment]
I will add a check for root. Thanks @TomTom101 .
