### ISSUE TITLE
Homematic docker on QNAP

### ISSUE THREAD

**Issue by DominikBaer** [angelnu/docker-ccu2#12]
Hi 
I am wondering whether it would bee possible to make the homematic docker image working on QNAP ARM based or Intel based?

Thanks

**Comment by angelnu** [comment]
Hi,
it might work out of the box if you do not need to use the the homematic PCB adapter.

I will release in the next minutes a version that will not enforce running in a known platform so any ARM platform should not work.

As soon as ELV releases the USB adapter for Homematic IP I will add support for it. I expect than then any platform should be able to use it within a docker container.

**Comment by angelnu** [comment]
New docker container available - @DominikBaer please give it a try and let me know.
