### ISSUE TITLE
update CUXD 2.0.0 fails

### ISSUE THREAD

**Issue by omo2002** [angelnu/docker-ccu2#18]
Hi,
just trying to get the latest CUXD release 2.0.0 up and running but it fails.
I was manually installing the softare like I did at https://github.com/angelnu/docker-ccu2/issues/6.

Seams there is a problem with the executables e.g. update_addon and cuxd. They don't even start ("not found"). I tried to trace this problem back, in my eyes it exists since cuxd 1.10, cuxd 1.9 is the latest one that is running within the docker container.
Any ideas how to trace this problem or even get a solution ?

**Comment by angelnu** [comment]
@omo2002 - so you extracted the tarball and there is no update_script ?

If you post a link to the tarball you are trying I can take a look.

**Comment by omo2002** [comment]
No , sorry for being not precise enough.
There is an update_script, but it cannot be run in the container. Outside on Jessie OS Level it works.

Here is the link
https://homematic-forum.de/forum/download/file.php?id=48020&sid=1d1a5168068969a1213e914b4dc45292

**Comment by angelnu** [comment]
The update_addon does not find the loader. It continues after running `ln -s /lib/ld-linux.so.3 /lib/ld-linux-armhf.so.3`.

If this is needed I can add it to the docker image.

**Comment by omo2002** [comment]
Thanks, I will check when I have access to my PC again. Regarding the Image: yes please add it, also to the Dockerfile.

**Comment by omo2002** [comment]
Thanks, the process is starting now. But I have problems with cuxd itself. Will keep you posted.

**Comment by angelnu** [comment]
I released an updated docker container with the symbolic link

**Comment by omo2002** [comment]
angelnu, thanks for th hint, cuxd in the current version is working now for me. problem was, that I took the raspberrymatic version, which is wrong. The right one is the "normal" one.
I did not check the new image, but I believe it is working fine.
