### ISSUE TITLE
Cannot build using Raspbian Lite - Stretch

### ISSUE THREAD

**Issue by andreheuer** [angelnu/docker-ccu2#20]
Hi all,

as I have some problems using the pre-build version of the image (groups are not working properly), I wanted to build the docker image again.
However, after cloning the repo, copying settings.template and running build.sh, I get the following error:
`root@smarthome:~/docker-ccu2# ./build.sh`
`Sending build context to Docker daemon  121.3kB`
`Step 1/17 : FROM python:alpine as builder`
`alpine: Pulling from library/python`
`no matching manifest for unknown in the manifest list entries`
`root@smarthome:~/docker-ccu2# `

I am running on a RPi 3
`root@smarthome:~/docker-ccu2# uname -a`
`Linux smarthome 4.14.58v7-aufs #1 SMP Sat Jul 28 20:40:59 CEST 2018 armv7l GNU/Linux`

Has anyone an idea?

BR,
André

**Comment by angelnu** [comment]
The Alpine version of Python for arm64 does not seem to be built.

I uploaded a branch (ubuntu) that uses Ubuntu - please try it. It takes longer to download but it should be more compatible with other devices. The size of the resulting image will not be affected.

**Comment by andreheuer** [comment]
I could now build the container image. Thank you!

However, after deploying the container (without any configuration), I still get the connection errors for the interfaces for VirtualDevices, HmIP-RF, and BidCos-RF, and thus heating groups are still not working :-(

**Comment by angelnu** [comment]
I only use the wireless HM devices so I cannot test the others. There is other new HW for HM-IP that should work with HM-IP: you could configure it using the rfd.conf
