### ISSUE TITLE
please provide docker image with latest ccu2 firmware

### ISSUE THREAD

**Issue by omo2002** [angelnu/docker-ccu2#22]
Hi,
I tried to build the latest image (2.35.16) by myself, but the built docker container is not starting propperly and remains in status restarting.
I used the workaround with the ubunto base image.

So, can you please provide an updated image on dockerhub ?

thanks for your efforts.

**Comment by angelnu** [comment]
Built and uploaded version 2.35.16 - it works for me but the new "device firmware - overview" does nothing.
