### ISSUE TITLE
Deploy CCU2

### ISSUE THREAD

**Issue by JackGruber** [angelnu/docker-ccu2#26]
Hi,

a deploy of a CCU2 version does not work, for CCU3 the deploy works. 

```
./deploy.sh
Unable to find image 'angelnu/ccu:2' locally
docker: Error response from daemon: manifest for angelnu/ccu:2 not found.
```

**Comment by angelnu** [comment]
@JackGruber - for the CCU2 please use the ccu2 branch -> I will add a checking to the build/deploy to warn about this.

**Comment by JackGruber** [comment]
oh, i didn't see that one.

**Comment by angelnu** [comment]
Added check
