### ISSUE TITLE
Import YAHM Backup

### ISSUE THREAD

**Issue by JackGruber** [angelnu/docker-ccu2#27]
Hi,

after I import a Backup from CCU YAHM, i get the follow errors.
![2018-12-28 13_05_08-homematic webui](https://user-images.githubusercontent.com/24863925/50514882-6ca0ca00-0aa1-11e9-88ae-9f0b4b1c97c6.jpg)![2018-12-28 13_04_56-homematic webui](https://user-images.githubusercontent.com/24863925/50514883-6ca0ca00-0aa1-11e9-8c82-c4b9b1cdd387.jpg)![2018-12-28 13_05_02-homematic webui](https://user-images.githubusercontent.com/24863925/50514884-6ca0ca00-0aa1-11e9-8c08-9c5a7ef2f3cf.jpg)

`docker logs -t ccu`
[docker_logs.log](https://github.com/angelnu/docker-ccu2/files/2714819/docker_logs.log)

**Comment by angelnu** [comment]
The log shows that the rfd service did not come up after restoring the backup. The HMipServer did on the first boot after restoring the backup but it did not on the second: did you change something between both?

Can you please attach your `/var/lib/docker/volumes/ccu_data/_data/etc/config/rfd.conf` (a sym link is created by deploy.sh into your local folder) and the output of `docker exec ccu cat /tmp/hmserver.log`?

**Comment by JackGruber** [comment]
No i change nothing after the backup import. 

**rfd.conf**
```
# TCP Port for XmlRpc connections
Listen Port = 32001

Log Destination = Syslog
Log Identifier = rfd
Log Level = 1

Persist Keys = 1

# PID File = /var/rfd.pid
# UDS File = /var/socket_rfd

Device Description Dir = /firmware/rftypes
Device Files Dir = /etc/config/rfd
Key File = /etc/config/keys
Address File = /etc/config/ids
Firmware Dir = /firmware
Replacemap File = /firmware/rftypes/replaceMap/rfReplaceMap.xml
Fire NACK Error Events = true
Improved Coprocessor Initialization = false

[Interface 0]
Type = CCU2
ComPortFile = /dev/mmd_bidcos
#AccessFile = /dev/null
#ResetFile = /dev/ccu2-ic200
```


**rfd -l 0 -c**
```
Config file is /etc/config/rfd.conf
2018/12/28 14:35:03.869 <Info> BidCoS-Service started
2018/12/28 14:35:03.870 <Info> XmlRpc Server is listening on TCP port 32001
2018/12/28 14:35:03.874  RFFirmwareManager: Registered user-deployed device firmware version 1.2 for device id 219.
2018/12/28 14:35:03.874  RFFirmwareManager: Registered user-deployed device firmware version 1.3 for device id 173.
2018/12/28 14:35:03.874  RFFirmwareManager: Registered user-deployed device firmware version 1.4 for device id 149.
2018/12/28 14:35:03.874  RFFirmwareManager: Registered user-deployed device firmware version 2.5 for device id 172.
2018/12/28 14:35:03.875 <Error> Init failed. Parameter 'AccessFile' not set in bidcos configuration file.
2018/12/28 14:35:03.876 <Error> No BidCoS-Interface available
2018/12/28 14:35:03.876 <Warning> Error initializing interfaces
```

**eq3configcmd update-coprocessor -p /dev/mmd_bidcos -c -se -d /firmware**
`2018/12/28 14:36:46.198 <Info> SerialNumber: NEQ1332020`

**eq3configcmd update-coprocessor -p /dev/mmd_bidcos -c -v -d /firmware**
`2018/12/28 14:37:20.928 <Info> Version: 2.8.6`

**[hmserver.log](https://github.com/angelnu/docker-ccu2/files/2714952/hmserver.log)**

**Comment by angelnu** [comment]
Please stop the container, delete `/var/lib/docker/volumes/ccu_data/_data/etc/config/rfd.conf`and start it again so that the rfd.conf is copied fresh from the template.

If it does not work again then please attach again the docker logs, rfd.conf and hmserver.log.

**Comment by JackGruber** [comment]
No, unfortunately not.

**/var/lib/docker/volumes/ccu_data/_data/etc/config/rfd.conf**
```
# TCP Port for XmlRpc connections
Listen Port = 32001

Log Destination = Syslog
Log Identifier = rfd
Log Level = 1

Persist Keys = 1

# PID File = /var/rfd.pid
# UDS File = /var/socket_rfd

Device Description Dir = /firmware/rftypes
Device Files Dir = /etc/config/rfd
Key File = /etc/config/keys
Address File = /etc/config/ids
Firmware Dir = /firmware
Replacemap File = /firmware/rftypes/replaceMap/rfReplaceMap.xml
Fire NACK Error Events = true
Improved Coprocessor Initialization = false

[Interface 0]
Type = CCU2
ComPortFile = /dev/mmd_bidcos
#AccessFile = /dev/null
#ResetFile = /dev/ccu2-ic200
```

**Lofiles:**
[hmserver.log](https://github.com/angelnu/docker-ccu2/files/2715151/hmserver.log)
[docker_logs.log](https://github.com/angelnu/docker-ccu2/files/2715152/docker_logs.log)

**Comment by angelnu** [comment]
This looks like an old version of the container, before I removed the patch to disable the _Improved Coprocessor Initialization_. Could you please do a `docker pull angelnu/ccu:3` to ensure you are on the latest?

**Comment by JackGruber** [comment]
OK, I think there's another problem.

I delete the volumes and containers and make a docker and git pull.
The first start works fine, after a restart the HmIP-RF ist not workin anymore. 
At this point i have not imported the CCU backup.

[hmserver.log](https://github.com/angelnu/docker-ccu2/files/2715463/hmserver.log)
[docker_logs.log](https://github.com/angelnu/docker-ccu2/files/2715464/docker_logs.log)

**Comment by JackGruber** [comment]
OK, after the import of the Backup the HmIP-RF  is workink, but the BidCos-RF not.
[docker_logs_import.log](https://github.com/angelnu/docker-ccu2/files/2715496/docker_logs_import.log)
[hmserver_import.log](https://github.com/angelnu/docker-ccu2/files/2715497/hmserver_import.log)


**rfd.conf**
```
# TCP Port for XmlRpc connections
Listen Port = 32001

Log Destination = Syslog
Log Identifier = rfd
Log Level = 1

Persist Keys = 1

# PID File = /var/rfd.pid
# UDS File = /var/socket_rfd

Device Description Dir = /firmware/rftypes
Device Files Dir = /etc/config/rfd
Key File = /etc/config/keys
Address File = /etc/config/ids
Firmware Dir = /firmware
Replacemap File = /firmware/rftypes/replaceMap/rfReplaceMap.xml
Fire NACK Error Events = true
Improved Coprocessor Initialization = false

[Interface 0]
Type = CCU2
ComPortFile = /dev/mmd_bidcos
#AccessFile = /dev/null
#ResetFile = /dev/ccu2-ic200
```

**Comment by JackGruber** [comment]
I found the problem.

I changed in the rfd.conf `Improved Coprocessor Initialization` to `true`

**Comment by angelnu** [comment]
Good. I added a note to the README about how to deal with the broken RFD after restoring a backup.
