### ISSUE TITLE
Don't recognize HW

### ISSUE THREAD

**Issue by online-junkie** [angelnu/docker-ccu2#9]
Hi, 
first of all I need to say a docker for ccu2 is a great idea. Many thanks for this.
However any new idea has its challenges and the one I cannot overcome is the following.

When I execute the following:
root@raspberrypi:/# docker run -i -t angelnu/ccu2
The output is:
Checking device
grep: /sys_org/firmware/devicetree/base/model: No such file or directory
grep: /sys_org/firmware/devicetree/base/model: No such file or directory
cat: can't open '^/model': No such file or directory
Do not recognize HW  -> Exiting

On my raspberry of course the directory /sys_org does not exist.
So I've created a Symlink but the issue still exist

cat /sys_org/firmware/devicetree/base/model 
shows: 
Raspberry Pi 3 Model B Rev 1.2

I think it is same as issue #4  and the path for raspberry devices need to be corrected.

BR,
Kurt

**Comment by angelnu** [comment]
@online-junkie - you are missing the additional parameters to share the HW with the docker container.

Check: https://hub.docker.com/r/angelnu/ccu2/

**Comment by online-junkie** [comment]
What I did so far is:

# A short howto install homematic and node-red engine on the latest rasperian
# Date: 30.06.2017

# First Download + Install Jessie Lite
# https://www.raspberrypi.org/downloads/raspbian/
# image it with Win32Disk
# https://sourceforge.net/projects/win32diskimager/ 

#configure raspi-config
sudo raspi-config
# configure locals and extend boot partition

# configure hm-mod-rpi-pcb
sudo -i
echo "enable_uart=1" >> /boot/config.txt 
echo "dtoverlay=pi3-miniuart-bt" >> /boot/config.txt # Nur beim Pi3 notwendig
echo "core_freq=250" >> /boot/config.txt 
sed -i s/'\bconsole=serial0,115200 //' /boot/cmdline.txt
systemctl disable serial-getty@ttyAMA0.service
reboot

#login as pi user
sudo -i
mkdir /opt
cd /opt

sudo apt-get install git
curl -ks https://packagecloud.io/install/repositories/Hypriot/Schatzkiste/script.deb.sh | sudo bash
sudo apt-get install docker-hypriot=1.10.3-1
sudo sh -c 'usermod -aG docker $SUDO_USER'
sudo systemctl enable docker.service

#clone locally
sudo docker run --name ccu2 -d - --net=host -restart=always -e PERSISTENT_DIR=/mnt -v /dev:/dev_org -v /sys:/sys_org -v ccu2_data:/mnt --device=/dev/ttyAMA0:/dev_org/ttyAMA0:rwm angelnu/ccu2

But still the hm-mod-rpi-pcb board doesn't work.
Am I right the board emulates the standard RF-LAN gateway in this case?

Am I right to configure it as a

**Comment by online-junkie** [comment]
The issue can be closed, the above configuration works perfectly as well as the docker image.
My problem was a defect HM-MOD-RPI-PCB board. After soldering a new one and placing this on the raspi GPIO I can introduce new devices to my new docker-ccu2 :-)

Great work angelnu!!!

**Comment by angelnu** [comment]
Good that you found the issue!
